version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file: env.local
  manage:
    build: .
    entrypoint: /usr/local/bin/python /app/manage.py
    command: shell_plus
    volumes:
      - .:/app
    depends_on:
      - database
    env_file: env.local
  tests:
    build:
      context: .
    command: test
    depends_on:
      - database
    entrypoint: /usr/local/bin/python /app/manage.py
    restart: 'no'
    volumes:
      - ./:/app
    env_file: env.tests
  database:
    restart: always
    image: postgres
#    volumes:
#      - ./docker/postgres/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      - POSTGRES_DB=reallylonglink
      - POSTGRES_USER=reallylonglink
      - POSTGRES_PASSWORD=reallylonglink
