web:
  restart: on-failure
  build: .
  links:
    - database
  ports:
    - 8000:8000
  volumes:
    - .:/reallylonglink/
    - ./envdir/development/:/envdir/
  environment:
    - PYTHONPATH=/reallylonglink/
  command: envdir /envdir python manage.py runserver 0.0.0.0:8000

database:
  restart: always
  image: postgres:9
  volumes_from:
    - data
  volumes:
    - ./docker/postgres/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

data:
  restart: no
  image: postgres:9
  volumes:
    - /var/lib/postgresql
  command: /bin/true
